### ISSUE TITLE
weekday and weekends? aggregation?

### ISSUE THREAD

**Issue by uvsq22006942** [openshs/openshs#11]
[](url)Hello @nashamri, I have one question and a problem, the question is : 
how to specify the simulation if it is weekday or weekend (all the csv output are being weekday)

the problem is, after generating several simulation, I am doing aggregation but it does not work the error is : 

$ ./openshs aggregate -d 30 -sd 2016-02-08 -tm 15
Traceback (most recent call last):
  File "./openshs", line 168, in <module>
    main()
  File "C:\Users\houss\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\houss\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\houss\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\houss\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\houss\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "./openshs", line 154, in aggregate
    rep_rows = pool.generate_sample(header=False)
  File "C:\Users\houss\OneDrive\Desktop\openshs-master (1)\openshs-master\app\repeater.py", line 199, in generate_sample
    if strip_sample_and_idx_from_key(picked_labels[-1]) == strip_sample_and_idx_from_key(picked_labels[-2]):
**IndexError: list index out of range**

thank you

**Comment by Chaalse** [comment]
For aggregate to work properly you need one file of each type weekday/weekend (with their respective morning/evening context) in the temp folder. 
And each of this simulations must take enough hours, to make hours transccur in a simulation session press Z and then space. An UI will open and you can pick an activity and set the time it takes (in seconds), clicking OK will increase time counter in the amount you specified.
