### ISSUE TITLE
Issue in Starting the Blender Session

### ISSUE THREAD

**Issue by khalidsophee** [openshs/openshs#15]
New@DESKTOP-EDQ83P4 MINGW64 ~/Desktop/openshs/app (master)
$ ./openshs start -c morning
Starting the morning context.
What's the starting time? [2016-02-01 08:00:00]:
Traceback (most recent call last):
  File "C:\Users\New\Desktop\openshs\app\openshs", line 165, in <module>
    main()
  File "C:\Users\New\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\New\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\New\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\New\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\New\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\New\Desktop\openshs\app\openshs", line 101, in start
    start_dt = click.prompt("What's the starting time?",
  File "C:\Users\New\AppData\Local\Programs\Python\Python310\lib\site-packages\click\termui.py", line 173, in prompt
    result = value_proc(value)
  File "C:\Users\New\Desktop\openshs\app\openshs", line 24, in validate_dt
    dt = datetime.strptime(value, "%Y-%m-%d %H-%M-%S")
TypeError: strptime() argument 1 must be str, not datetime.datetime

**Comment by khalidsophee** [comment]
Hello, I have followed all the steps to install OpenSHS on Windows using the video provided in the README file. However, I encountered an error when attempting to launch a simulation.

**Comment by khalidsophee** [comment]
$ ./openshs start -c morning
Starting the morning context.
What's the starting time? [2016-02-01 08:00:00]: 2016-02-01 08:00:00
Error: Please enter a valid datetime
What's the starting time? [2016-02-01 08:00:00]: 2016-02-01 08-00-00
Error: Please enter a valid datetime
What's the starting time? [2016-02-01 08:00:00]:
