### ISSUE TITLE
Cannot starts a blender session with the morning context simulation

### ISSUE THREAD

**Issue by longnp93** [openshs/openshs#4]
Hi,

I am following the "Quick Start" instruction but I cannot starts a blender session with the morning context simulation. I am running on Windows, Python 3.7 and installed click module and indexed.py.

Here is the error:

D:\Download\openshs-openshs-11a8c42\app>python openshs start -c morning
Starting the morning context.
What's the starting time? [2016-02-01 08:00:00]:
Traceback (most recent call last):
  File "openshs", line 165, in <module>
    main()
  File "C:\Users\SONY\AppData\Local\Programs\Python\Python37\lib\site-packages\c
lick\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\SONY\AppData\Local\Programs\Python\Python37\lib\site-packages\c
lick\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\SONY\AppData\Local\Programs\Python\Python37\lib\site-packages\c
lick\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\SONY\AppData\Local\Programs\Python\Python37\lib\site-packages\c
lick\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\SONY\AppData\Local\Programs\Python\Python37\lib\site-packages\c
lick\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "openshs", line 117, in start
    subprocess.call(["blender", CONTEXTS[context]['exe']], stdout=subprocess.DEV
NULL, stderr=subprocess.DEVNULL)
  File "C:\Users\SONY\AppData\Local\Programs\Python\Python37\lib\subprocess.py",
 line 304, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\SONY\AppData\Local\Programs\Python\Python37\lib\subprocess.py",
 line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Users\SONY\AppData\Local\Programs\Python\Python37\lib\subprocess.py",
 line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Thanks,

**Comment by nashamri** [comment]
@longnp93 hey there,
Maybe this video will help you find the issue when you installed OpenSHS on window
https://www.youtube.com/watch?v=GHHsXPvaAnY

**Comment by longnp93** [comment]
Thank you @nashamri

**Comment by nashamri** [comment]
@longnp93 you are welcomed. I've added that video to the README file. :+1:
